### ISSUE TITLE
Make context a parameter in room database

### ISSUE THREAD

**Issue by AdamMc331** [LouisCAD/Splitties#11]
Currently the room module uses `appCtx` for the context when referencing a Room database - https://github.com/LouisCAD/Splitties/blob/master/arch-room/src/main/java/splitties/arch/room/Room.kt#L25

This will be okay in most cases, but we should make it a default parameter so the user has the _option_ to provide a specific context if they prefer.

**Comment by AdamMc331** [comment]
My suggestion:

```kotlin
inline fun <reified DB : RoomDatabase> roomDb(name: String, context: Context = appCtx, config: DbConfig<DB> = {}): DB {
    return Room.databaseBuilder(context, DB::class.java, name).apply(config).build()
}
```

**Comment by LouisCAD** [comment]
Your suggestion allows to not force to use named parameter for the database name when you leave the default context. However, encouraging named `name` parameter may be a good thing that would be done by putting the `Context` parameter first. Thoughts?

An alternative which I like is to write a `roomDb(…)` with the `Context` parameter first, following the convention seen in Android, with an inline overload passing `appCtx`.

**Comment by AdamMc331** [comment]
If you put context first, you're forcing the named parameter. Meaning if I don't care about context, I must do `roomDb(name = "louiscad.db")`. 

Personally, I don't like the UX. Named parameters are beneficial if I want to set a parameter that's not up front or not always used, but I wouldn't want to use it _all the time_. The way you have it written currently, you recognize that in many cases the user will only care enough to pass in the name of the database. I think the API should stay designed in such a way to reflect that.

**Comment by LouisCAD** [comment]
Here's the overload alternative which is the best IMHO:
```kotlin
inline fun <reified DB : RoomDatabase> roomDb(context: Context, name: String, config: DbConfig<DB> = {}): DB {
    return Room.databaseBuilder(context, DB::class.java, name).apply(config).build()
}

inline fun <reified DB : RoomDatabase> roomDb(name: String, config: DbConfig<DB> = {}): DB {
    return roomDb(appCtx, name, config)
}
```

**Comment by LouisCAD** [comment]
This has just been fixed. This will allow to pass `directBootCtx` or maybe some other `Context`, which is important for some apps. Thanks for reporting!
