### ISSUE TITLE
What's the difference between alert dialogs in Anko and Splitties

### ISSUE THREAD

**Issue by qbait** [LouisCAD/Splitties#129]
Thank you for your work @LouisCAD. Could you point out what's the difference between alert dialogs in Anko and Splitties, please?

**Comment by LouisCAD** [comment]
Hi @qbait, Splitties alert dialogs don't rely on the whole library, so you're including much less code into your app than with Anko. You can have both in your project and also compare the implementations, sources are included with the releases of Splitties (and Anko should too).
