### ISSUE TITLE
px to dp [no use case yet]

### ISSUE THREAD

**Issue by loicteillard** [LouisCAD/Splitties#157]
Please add the reverse feature (dp to px) to splitties-dimensions if you agree, thanks

**Comment by LouisCAD** [comment]
Alright, I'm closing this issue. If you want other features that satisfy a use case (even if it's just a vague idea), or if you want some of your extensions to become part of Splitties, feel free to comment there, reach out on Kotlin Slack, Twitter DM, or open a new issue.
