### ISSUE TITLE
DslMarker

### ISSUE THREAD

**Issue by Leland-Takamine** [LouisCAD/Splitties#167]
Should the DSL modules be using [@DslMarker](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/-dsl-marker/index.html)?

**Comment by LouisCAD** [comment]
Hi, I looked at it in the past, but what I saw was that it only worked with classes that you control. Splitties Views DSL is almost all extensions for existing classes from Android and AndroidX, so this is not possible.

However, I am open to discuss making a DSL for Views that uses custom class(es) (possibly inline, wrapping the actual `View`.
