### ISSUE TITLE
Support MaterialAlertDialogBuilder

### ISSUE THREAD

**Issue by LouisCAD** [LouisCAD/Splitties#168]
This is currently not released in a stable version of Material Components.

Relevant doc: https://github.com/material-components/material-components-android/blob/master/docs/components/Dialog.md

Relevant code: https://github.com/material-components/material-components-android/blob/master/lib/java/com/google/android/material/dialog/MaterialAlertDialogBuilder.java

**Comment by william-reed** [comment]
I was just wondering about this since I saw docs in their repo but couldn't access it in my project

**Comment by LouisCAD** [comment]
Released in version 3.0.0-alpha07.
