### ISSUE TITLE
Ensure multiple permissions

### ISSUE THREAD

**Issue by TemMax** [LouisCAD/Splitties#197]
Hi! I faced with case, when I need to ensure a few permissions, for camera and external storage at one time for example. How I can make this?

**Comment by LouisCAD** [comment]
Hi, calling it twice with each permission in the same coroutine is the
simplest way to achieve this. That also enables easier handling of one
permission being granted and one being denied.

**Comment by TemMax** [comment]
Ok. But when I try to call it twice I see rationale before e!sure second permission. But I don't want a rationale for first permissions ask. (I set "showRationaleBeforeFirstAsk" to false). You can try it

**Comment by LouisCAD** [comment]
Isn't that because you initially denied that permission?

**Comment by TemMax** [comment]
Sorry. I want to say that when I ensure two permissions (for camera and storage for example) before requesting second permission rationale is showing.

**Comment by LouisCAD** [comment]
Hi, I just verified and it works exactly as expected on first ask.

I added those 2 permissions in the manifest, and the code to request them in `PermissionsSampleActivity`:
```kotlin
ensurePermission(
    permission = Manifest.permission.ACCESS_FINE_LOCATION,
    askDialogTitle = "Please, location",
    askDialogMessage = "Promise we won't use it.",
    showRationaleBeforeFirstAsk = false // NO RATIONALE ON FIRST ASK
) { finish(); throw CancellationException() }
ensurePermission(
    permission = Manifest.permission.READ_CONTACTS,
    askDialogTitle = "Please, contacts. All of it.",
    askDialogMessage = "Promise we won't use it.",
    showRationaleBeforeFirstAsk = false // NO RATIONALE ON FIRST ASK
) { finish(); throw CancellationException() }
```
On first ask, it starts by asking location, and on grant, it asks for contacts too, without showing any rationale.
