### ISSUE TITLE
Android resource linking failed

### ISSUE THREAD

**Issue by tanks007** [LouisCAD/Splitties#205]
Here is the full stack-trace:

`Output: ....app/build/intermediates/incremental/mergeDebugResources/merged.dir/values/values.xml:322: error: resource android:attr/fontVariationSettings not found.
..../app/build/intermediates/incremental/mergeDebugResources/merged.dir/values/values.xml:322: error: resource android:attr/ttcIndex not found.
error: failed linking references.

Command: /home/user/.gradle/caches/transforms-2/files-2.1/4f4a1d0afe21c07f5aacc6b2b54824b6/aapt2-3.2.0-4818971-linux/aapt2 link -I\
        /home/user/Android/Sdk/platforms/android-27/android.jar\
        --manifest\
       .../app/build/intermediates/merged_manifests/debug/processDebugManifest/merged/AndroidManifest.xml\
        -o\
       .../app/build/intermediates/processed_res/debug/processDebugResources/out/resources-debug.ap_\
        -R\
        @.../app/build/intermediates/incremental/processDebugResources/resources-list-for-resources-debug.ap_.txt\
        --auto-add-overlay\
        --java\
       .../app/build/generated/not_namespaced_r_class_sources/debug/processDebugResources/r\
        --custom-package\
        com.resocoder.ankotutorial\
        -0\
        apk\
        --output-text-symbols\
       .../app/build/intermediates/symbols/debug/R.txt\
        --no-version-vectors
Daemon:  AAPT2 aapt2-3.2.0-4818971-linux Daemon #0`

**Comment by LouisCAD** [comment]
How is that related to Splitties?

**Comment by tanks007** [comment]
This error occurred while adding the splitties view dsl dependency, i am adding 3.0.0-alpha06, AS version is 3.4.2 and gradle version 4.4

**Comment by LouisCAD** [comment]
I saw you post in the #splitties channel on Kotlin's Slack. The issue is your project is not using AndroidX, but Splitties requires it.
I put a migration guide and Kotlin script here: https://github.com/LouisCAD/Splitties/releases/tag/v3.0.0-alpha01
Feel free to reach out if it doesn't go as expected.
