### ISSUE TITLE
Version 3.0.0 blockers

### ISSUE THREAD

**Issue by LouisCAD** [LouisCAD/Splitties#216]
- [x] Setup GitHub Actions to publish on all platforms
- [x] Implement dependencies refresh (#215)
- [x] Update AndroidX dependencies to latest stable versions
- [x] Remove overlap with latest AndroidX KTX dependencies (with deprecation cycle in alpha/beta versions)
- [x] Have `dp` and `dip` overloads simplified. Takes `Int`, returns `Int`, takes `Float`, returns `Float`.
- [x] Review documentation and clean outdated content
- [x] Update documentation to cover the new features and changes
~Polish Gradle plugin (#214)~

**Comment by jmfayard** [comment]
- [ ] sorting dependencies version will be configurable in v0.7.0 https://github.com/jmfayard/buildSrcVersions/issues/65

**Comment by jmfayard** [comment]
For 3.0 it would be good to have a task `./gradlew migrateToSplitties` https://github.com/LouisCAD/Splitties/issues/222

**Comment by LouisCAD** [comment]
This is progressing again.
- I optimized the CI so it's currently about as fast as GitHub Actions allows.
- I updated my `Releasing.kts` script to let the GitHub Actions upload the artifacts to bintray.
- Did a few improvements on Views DSL ConstraintLayout that I wanted to do.

Most of the remaining work is now documentation, and the migrateToSplitties Gradle task.

Regarding that task, I'm wondering if I should not do it later so I focus on refreshVersions instead.

**Comment by jmfayard** [comment]
@LouisCAD focus on realeasing 3.0.0!
 
We can improve refreshVersion and do migrateToSplitties later. 
Just add a note for existing users that you have a migration plan that is coming and that if they are interested, they should star some issue so that we can warn them when it's ready

**Comment by LouisCAD** [comment]
Last steps are:
1. Making the release process the least flaky it can be (bintray's unreliability doesn't help)
2. Mention/acknowledge Jetpack Compose in Views DSL README
3. Improve the main README with structure
4. Add refreshVersions syntax for adding the dependency, and show if a split is part of several fun packs
5. Review all the APIs to see if some need to be marked as experimental
6. Release the last 1.3 compatible Kotlin release(s)
7. Upgrade to Kotlin 1.4
8. Release RC for Kotlin 1.4

**Comment by LouisCAD** [comment]
I don't see any blockers now, closing.
