### ISSUE TITLE
Add GitHub actions to check and publish libraries on all multiplatform targets

### ISSUE THREAD

**Issue by LouisCAD** [LouisCAD/Splitties#218]
That will allow me to iterate faster as building and publishing Splitties will no longer monopolize my machine for 5 minutes, and I'll be able to support Windows and Linux.

I need to understand if I need Docker or not for the actions or some steps/jobs of them. Might depend on the platform.

Docs link: https://help.github.com/en/categories/automating-your-workflow-with-github-actions
In addition to the docs, this repo might be helpful: https://github.com/sdras/awesome-actions

**Comment by LouisCAD** [comment]
Continue reading here: https://help.github.com/en/articles/workflow-syntax-for-github-actions#onevent_nametypes

**Comment by jmfayard** [comment]
Paul Merlin from Gradle has a ready to use Gradle Action
https://github.com/marketplace/actions/gradle-command

**Comment by LouisCAD** [comment]
Thank you very much for the link, I didn't know this was a thing!

**Comment by LouisCAD** [comment]
Done.
