### ISSUE TITLE
Launch documentation website powered by Orchid and Netlify

### ISSUE THREAD

**Issue by jmfayard** [LouisCAD/Splitties#226]
Hello, 

you did the hard part of documenting which is writing the content.

I recommend as a next step to put all those markdown files in a website Gradle module powered by Orchid

See https://github.com/JavaEden/Orchid

I use it for my own needs and find it good, less well known that Hugo, Jekyll, Gatsby, but it fits right in with our skills: Gradle, Kotlin.

The way to get started is to clone this repo
https://github.com/JavaEden/OrchidStarter

There is a **Deploy to netlify** button there that will get you a website running in no time.

Netlify takes care of the hosting (free since it's just HTML/CSS/JS files) and of the integration with **git**.

Then copy all your markdown files in the folder `src/orchid/resources/wiki`

Commit and Netlify will re-deploy the website generated by Orchid

**Comment by LouisCAD** [comment]
I guess this issue is now obsolete with the new website powered by Material for MKDocs.
