### ISSUE TITLE
Allow add/remove change listener to preferences

### ISSUE THREAD

**Issue by Zey-Uzh** [LouisCAD/Splitties#227]
A preferences change listener would be very helpful. For example, for integration with rx.

**Comment by LouisCAD** [comment]
The latest dev version (3.0.0-dev-042) integrates with `Flow` from kotlinx.coroutines (similar to RxJava's `Flowable`). The preference fields have a `valueFlow()` function and a `changesFlow()` function that you can use to listen to the latest values.

Does that satisfy your use case?

Note that you still have access to the underlying `SharedPreferences`, where you can set a listener yourself if you don't want to use the existing integration with `Flow`.

**Comment by vladimirfx** [comment]
Coroutines support is great, but for projects that don't rely on Coroutines is useless. It would be nice to have raw mechanism OnSharedPreferenceChangeListener accessible in addition to Coroutines or RxJava mechanisms.

**Comment by LouisCAD** [comment]
As I said, it is already available in the `Preferences` class, there's a `prefs` property of type `SharedPreferences`.

**Comment by vladimirfx** [comment]
Oh, sorry, I'm missing it because it protected. To use it fun should be added to our Preferences object.
Thank you very match!

**Comment by Zey-Uzh** [comment]
Thanks for answers!

**Comment by LouisCAD** [comment]
Yes, I made it `protected` because it gives access to a lower level API where mistakes are easier to do.
