### ISSUE TITLE
Question: how to expose bundle?

### ISSUE THREAD

**Issue by lde-exerp** [LouisCAD/Splitties#231]
@LouisCAD 

As I understand the bundle split helps you make type safe operations that use bundle, but hide the bundle itself (hence it's private). 
How do I expose a bundle from a BundleSpec as arguments to another object (E.g. as Navigation Component Arguments)

**Comment by LouisCAD** [comment]
Hi, you can use the `with` extension function for `Bundle` [defined here](https://github.com/LouisCAD/Splitties/blob/0ec1a317669876147ac39365f41be5f8b67c2e3e/modules/bundle/src/androidMain/kotlin/splitties/bundle/BundleAccessors.kt#L88) to use your BundleSpec on an arbitrary `Bundle`.

I didn't find a way to have smooth interop with AndroidX Navigation for now, and didn't invest much in it, but if you have some ideas to make it less manual, feel free to share them here.
