### ISSUE TITLE
Add LiveData observables for SharedPreferences

### ISSUE THREAD

**Issue by gajicm93** [LouisCAD/Splitties#233]
I'd like to be able to get a LiveData observable for any individual Preferences key. Here is the example implementation: https://gist.github.com/rharter/1df1cd72ce4e9d1801bd2d49f2a96810

**Comment by LouisCAD** [comment]
The dev version exposes Flow for all supported platforms (iOS, macOS,
Android) and with AndroidX Lifecycle LiveData KTX 2.2.0+ (released 2 days
ago), you can convert it to a LiveData with the extension for Flow (and
back to a Flow as well if ever needed).

I plan to release a new version of Splitties soon after I'm done updating
the docs, writing the changelog and deprecating overlap with stable
AndroidX artifacts.

That'll happen very soon, be sure to click watch and select "releases only".

**Comment by gajicm93** [comment]
Amazing, thank you! @LouisCAD

**Comment by gajicm93** [comment]
@LouisCAD Hi, I downloaded the latest dev version, but can't find anything about Flow in Preferences? Did something change from the last time we spoke? Thanks.

**Comment by LouisCAD** [comment]
Hi @gajicm93, I'm sorry I still didn't published a release. You can use the latest dev version (setup info in README, use version `3.0.0-dev-056`) to have it now.
I don't expect the API of preferences to change significantly or at all before the next release, so it should be future-proof enough.

**Comment by gajicm93** [comment]
> Hi @gajicm93, I'm sorry I still didn't published a release. You can use the latest dev version (setup info in README, use version `3.0.0-dev-056`) to have it now.
> I don't expect the API of preferences to change significantly or at all before the next release, so it should be future-proof enough.

That's what I'm using, but I can't find it anywhere. Can you post a code snippet how to use it? Thanks.

**Comment by LouisCAD** [comment]
Example usage from a `Preferences` subclass:
```kotlin
class SomePreferences private constructor() : Preferences(name = "someStuff") {

    val someFlow: Flow<Boolean>

    var somePrefField by boolPref("somePref", defaultValue = false).also {
        someFlow = it.valueFlow()
    }

    companion object : SuspendPrefsAccessor<SomePreferences>(::SomePreferences)
}
```

**Comment by gajicm93** [comment]
@LouisCAD Ahhh I get what you mean, but that's not a "real" Preferences observer and only propagates values that I set through my own Preference class.. That way I can't observe preferences written by some 3rd party library implementation, etc..

I was thinking about something like this being part of your library: https://gist.github.com/rharter/1df1cd72ce4e9d1801bd2d49f2a96810

But so far I'm using it successfully in combination with your library.

**Comment by LouisCAD** [comment]
@gajicm93 Well, the Android implementation of `valueFlow` is actually based on `OnSharedPreferenceChangeListener`, so it's "real" from your terms.

**Comment by LouisCAD** [comment]
@gajicm93 Here's the link to the implementation details: https://github.com/LouisCAD/Splitties/blob/49e2ee566730aaeb14b4fa9e395a677c3f214dba/modules/preferences/src/androidMain/kotlin/splitties/preferences/Changes.kt#L15

**Comment by gajicm93** [comment]
Ok I completely missed that `valueFlow()` method, even while reading your answer here on GitHub. Sorry my mistake, that's exactly what I was looking for.

Thank you for responding and sorry I wasted your time.

**Comment by LouisCAD** [comment]
That's a reminder people are using my work and that it'd be great for me to publish releases more often 😄
