### ISSUE TITLE
Setup One time donation link in funding metadata file

### ISSUE THREAD

**Issue by odahcam** [LouisCAD/Splitties#240]
Sponsor is great, but for individuals like me it isn't a reality yet to sponsor someone, a buck is **six times** one unity of my currency system. So I would like to make a small one time donation, just to say thanks. If 1/3 of all the users of my packages gave me one dollar I would be the happiest guy on open source, so I think this would be really nice. If you're interested you could setup a way for people like me to donate (e.g. PayPal or OpenCollective). Thanks a lot for this great package, it helped me a lot working with BLEGattCoroutines and saved me again just today.

**Comment by LouisCAD** [comment]
Hello @odahcam, thanks for offering to donate, and I'm glad my OSS work helped you!
I understand your concerns.

I'll update the sponsor links at some point to include my PayPal donation link.

In the meantime, here it is: https://www.paypal.me/louiscad (yes, you could have guessed it 😉)
