### ISSUE TITLE
The project is using an incompatible version of the Android Gradle plugin.

### ISSUE THREAD

**Issue by hqweb** [LouisCAD/Splitties#243]
ERROR: The project is using an incompatible version of the Android Gradle plugin.
Please update your project to use version 3.6.3.
Search in build.gradle files

**Comment by LouisCAD** [comment]
Hello, if you cloned the master branch, you need to update the version here: https://github.com/LouisCAD/Splitties/blob/0ec1a317669876147ac39365f41be5f8b67c2e3e/buildSrc/build.gradle.kts#L18

If you cloned the develop branch, you need to update the version here: https://github.com/LouisCAD/Splitties/blob/49e2ee566730aaeb14b4fa9e395a677c3f214dba/versions.properties#L7
