### ISSUE TITLE
Add experimental DataStore backed implementation of SharedPreferences

### ISSUE THREAD

**Issue by LouisCAD** [LouisCAD/Splitties#250]
Jetpack Datastore announcement blog post: https://android-developers.googleblog.com/2020/09/prefer-storing-data-with-jetpack.html?linkId=98693079

**Comment by Varsha-29** [comment]
@LouisCAD , can I take up this issue?

**Comment by LouisCAD** [comment]
Hi @Varsha-29, let's start with a prototype, based on the `develop` branch, so we see what challenges using the coroutines-and-flows-first `DataStore` API brings when we try to conform it to `SharedPreferences`.

**Comment by LouisCAD** [comment]
Once you have something worth looking at, please submit a draft PR so I can make an initial review and think about any design decisions that need to be done.

**Comment by Varsha-29** [comment]
Sure @LouisCAD . Will raise a draft PR

**Comment by LouisCAD** [comment]
Added in the latest snapshot, will be included in Splitties 3.0.0.

Here's the new doc section: https://github.com/LouisCAD/Splitties/tree/main/modules/preferences#using-androidx-datastore-instead-of-sharedpreferences-under-the-hood

The changes can be seen in #291

**Comment by LouisCAD** [comment]
Splitties 3.0.0 is out!
