### ISSUE TITLE
Migrate from jCenter to mavenCentral

### ISSUE THREAD

**Issue by joaoeudes7** [LouisCAD/Splitties#268]
Need migration of splitties packages, not available in repositories of mavenCentral.
JCenter deprecation and end of service: https://developer.android.com/studio/build/jcenter-migration

On Sync gradle receives:
Failed to resolve: com.louiscad.splitties:splitties-*****(all)

**Comment by LouisCAD** [comment]
I'm aware, it's planned.

**Comment by LouisCAD** [comment]
3.0.0-beta02 release for Kotlin 1.4.3x (should work fine for 1.5 if you're not depending on `@ExperimentalTime` APIs from Splitties) was published on MavenCentral successfully:
https://github.com/LouisCAD/Splitties/actions/runs/1009783995

Release for Kotlin 1.5 and future stuff coming soon now that I have a good and reliable releasing workflow.
