### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by MohamadKaramiDarabi** [LouisCAD/Splitties#272]
I cant build project. what's the problem? the error is:
Execution failed for task ':modules:mainthread:runCommonizer'.
> Could not resolve all files for configuration ':modules:mainthread:kotlinKlibCommonizerClasspath'.
   > Cannot resolve external dependency org.jetbrains.kotlin:kotlin-klib-commonizer-embeddable:1.4.10 because no repositories are defined.
     Required by:
         project :modules:mainthread

**Comment by LouisCAD** [comment]
Hello, do you still have the issue with the current main branch?

**Comment by MohamadKaramiDarabi** [comment]
Hello, yes.

**Comment by LouisCAD** [comment]
Which OS are you on?

**Comment by LouisCAD** [comment]
Also, can you try opening a fresh clone of the project in IntelliJ IDEA 2021.2 EAP? Community Edition will work fine if you don't have Ultimate.

**Comment by MohamadKaramiDarabi** [comment]
Linux

**Comment by MohamadKaramiDarabi** [comment]
Hello, can you recommended a good book to learn Gradle?

**Comment by LouisCAD** [comment]
I'm closing this issue because of lack of information on how to reproduce it. The project (latest revision of the `main` branch) builds fine on Linux in CI, and on Windows and macOS as well, in fact, most of the artifacts of the library are built and published from Linux (Ubuntu 20.04).

**Comment by MohamadKaramiDarabi** [comment]
Thank you. Its work well in windows.
