### ISSUE TITLE
Pull module specific documentation out of README

### ISSUE THREAD

**Issue by AdamMc331** [LouisCAD/Splitties#6]
Louis and I discussed this on Slack, to pull the paragraphs out and just leave the module name and link to documentation in README. (Wanted to create an issue as to not lose the idea).

**Comment by LouisCAD** [comment]
A short description of each module in the README could help to know what you're likely to find behind the link also.

**Comment by LouisCAD** [comment]
The details tag could also help: https://gist.github.com/ericclemmons/b146fe5da72ca1f706b2ef72a20ac39d

**Comment by LouisCAD** [comment]
Details tag added in 10866293c0ae1833cef507c78e5b2d6ce13b2400

**Comment by LouisCAD** [comment]
@AdamMc331 Could you let me know your thoughts on [this version of the README](https://github.com/LouisCAD/Splitties/blob/8a9c0eff6dee23839c96a19259de8808ad44003f/README.md) ?

**Comment by LouisCAD** [comment]
@AdamMc331 I finished the README update (no more TODOs):
https://github.com/LouisCAD/Splitties/blob/02bacac1404e6afbdf1029102148a8004a088a93/README.md
