### ISSUE TITLE
Complete module specific documentation.

### ISSUE THREAD

**Issue by AdamMc331** [LouisCAD/Splitties#9]
Some modules have their own README (which is great!) but not all of them do. For the sake of consistency (and also to complete the root README file) I think we should finish them. The ones that are missing are:

* arch-lifecycle
* arch-room
* bitflags
* bundle
* exceptions
* fragmentargs
* initprovider
* mainhandler
* preferences
* resources
* selectableviews
* snackbar
* stetho-init
* support-fragmentargs
* systemservices
* toast
* typesaferecyclerview
* uithread

**Comment by LouisCAD** [comment]
There have been new modules since then (totaling 33 for now). I'll review each of them to add or update their README.
